Adding password creation as .md file
platiagro/platiagro.github.io pull request #14
Opened 2021-09-13 12:26 UTC by andreluiz27

2021-09-13 17:09 UTC, andreluiz27 commented on content/pt/docs/Getting started/password-creation.md
> +  Veja como criar uma senha para um usuário do Kubeflow.
Aqui eu fiquei em dúvida se escrevia usuário ou usuário padrão, não sei se escrever só usuário foge muito do conceito

2021-09-13 17:09 UTC, andreluiz27 commented on content/pt/docs/Getting started/password-creation.md
> +É altamente __NÃO recomendado__ a utilização da senha predefinida do usuário padrão do Kubeflow em ambientes que precisam de segurança. Dito isto, segue abaixo as recomendações de criação de senha:
O texto em inglês fala em default user, só que eu achei que se eu fizesse a tradução como usuário predefinido iria ficar estranho, então fiz como usuário padrão, mas gostaria de uma outra opinião

2021-09-13 17:09 UTC, andreluiz27 commented on content/pt/docs/Getting started/password-creation.md
> +segue um exemplo de configmap: ![Config map file](/images/configmap.png)
Eu coloquei um print de uma imagem mostrando o trecho do configmap, mas não sei se ficou alinhado, não consegui ver o preview do markdown

2021-09-13 18:38 UTC, fberanizo requested changes

2021-09-13 18:38 UTC, fberanizo commented on content/pt/docs/Getting started/password-creation.md
> +É altamente __NÃO recomendado__ a utilização da senha predefinida do usuário padrão do Kubeflow em ambientes que precisam de segurança. Dito isto, segue abaixo as recomendações de criação de senha:
Acho que usuário padrão está bom :)

2021-09-13 18:38 UTC, fberanizo commented on content/pt/docs/Getting started/password-creation.md
> +segue um exemplo de configmap: ![Config map file](/images/configmap.png)
Acho que está certo, sim.

2021-09-13 18:38 UTC, fberanizo commented on content/pt/docs/Getting started/password-creation.md
> +```
@andreluiz27 acho que  seria interessante ensinar como instalar as bibliotecas passlib e bcrypt:
`pip install passlib[bcrypt]` além de deixar claro que você precisa do Python e do Pip...

2021-09-13 18:38 UTC, fberanizo commented on content/pt/docs/Getting started/password-creation.md
> +obs:será solicitada a senha que deseja ser transformada em hash
@andreluiz27 melhor mostrar um print desta etapa também (e deixar mais claro o que é o hash).

2021-09-13 18:38 UTC, fberanizo commented on content/pt/docs/Getting started/password-creation.md
> +1. considere o usuário padrão com o email `user@example.com`, basta escolher uma senha para esse usuário e em seguida transformá-la em uma hash utilizando a lib `bcrypt` do python, segue um trecho de
@andreluiz27 apesar do usuário padrão do kubeflow ser `user@example.com` / `12341234`, na platiagro o usuário padrão é `platiagro` / `platiagro1234`.

2021-09-13 18:38 UTC, fberanizo commented on content/pt/docs/Getting started/password-creation.md
> +linkTitle: Criação de senha para usuário kubeflow
@andreluiz27 apesar de por baixo dos panos usamos o kubeflow, acho que fica confuso falar senha do "kubeflow". O usuário no final das contas vai acessar as interfaces da platiagro com esta senha. 
Acredito que fica melhor Criação de senha para usuário da PlatIAgro

2021-09-13 18:38 UTC, fberanizo commented on content/pt/docs/Getting started/password-creation.md
> +  Veja como criar uma senha para um usuário do Kubeflow.
Está okay. Só deixo a mesma recomendação de trocar "Kubeflow" por "PlatIAgro"

2021-09-14 16:24 UTC, fberanizo approved these changes

2021-09-14 16:24 UTC, merged